script: scripts/run_all.sbatch
sbatch_args:
  - --job-name=sniper-llc-16mb-16w
  - --output=logs/%x-%A_%a.out
  - --error=logs/%x-%A_%a.err

env:
  SKIP_TRACE: 1
  SPEC_SIZE: ref
  SIM_N: 4
  ROI_M: 1000
  WARMUP_M: 100
  OUT_ROOT: "${PWD}/results/sniper_llc_16mb_16w_{timestamp}"

llc:
  sram:
    # ---- hard-coded from NVSim ----
    size_bytes: 16777216           # 16 MB
    assoc_ways: 16
    line_bytes: 64
    bus_width_bits: 512
    temp_k: 300.000
    tech_node_nm: 32
    read_hit_cycles: 14      # ceil(5.195 ns / 0.37594 ns)
    write_hit_cycles: 8     # ceil(2.973 ns / 0.37594 ns)
    energy:
      enabled: true
      e_read_hit_pJ: 1310        # 1.310 nJ
      e_write_hit_pJ: 1146       # 1.146 nJ
      e_miss_pJ: 1310            # NVSim miss ~= hit
      p_leak_mW: 45.118

  jans:
    # ---- hard-coded from NVSim STTRAM ----
    size_bytes: 16777216           # 16 MB
    assoc_ways: 16
    line_bytes: 64
    bus_width_bits: 512
    temp_k: 300
    tech_node_nm: 32
    read_hit_cycles: 12      # ceil(4.462 ns / 0.37594 ns)
    write_hit_cycles: 32     # ceil(11.909 ns / 0.37594 ns)
    energy:
      enabled: true
      e_read_hit_pJ: 1224        # 1.224 nJ
      e_write_hit_pJ: 874       # 0.874 nJ
      e_miss_pJ: 1224            # NVSim miss ~= hit
      p_leak_mW: 46.545

notes:
  - Cycle period (ns): 0.37594
  - Source SRAM: /home/skataoka26/COSC_498/devices/results/cache_triplet/C16MB_A16_W512_T300_20251002T012145Z/SRAM/SRAM.stdout.txt
  - Source JanS: /home/skataoka26/COSC_498/devices/results/cache_triplet/C16MB_A16_W512_T300_20251002T012145Z/STTRAM/STTRAM.stdout.txt
